/* AERIX browser-native UI: no bundler, framework, or Node runtime required. */
(() => {
  const app = document.querySelector('#app');
  const pages = new Set(['dashboard', 'gestures', 'calibration', 'settings']);
  const pageFromLocation = () => {
    const page = window.location.hash.replace(/^#\/?/, '').toLowerCase();
    return pages.has(page) ? page : 'dashboard';
  };
  // Keep the dashboard dormant until the user enters from the landing screen.
  // This prevents an idle landing page from opening a WebSocket or polling APIs.
  const state = { entered:false, starting:false, page:pageFromLocation(), locked:true, sensitivity:65, adaptive:true, status:'Connecting', mode:'gesture', calibration:{active:false,points:0,complete:false}, stats:{fps:0,latency:0,confidence:0,gesture:'none'}, clickSafety:{status:'LIMITED',warning:null}, activities:[], lastGesture:'none' };
  const friendly = v => String(v || 'none').replaceAll('_', ' ');
  const icon = char => `<span class="ui-icon" aria-hidden="true">${char}</span>`;
  const button = (action, text, className='') => `<button type="button" class="${className}" data-action="${action}">${text}</button>`;

  function startPage() {
    return `<section class="aerix-start-page" aria-label="AERIX startup screen"><div class="aerix-start-background"></div><div class="aerix-start-brand"><h1>AERI<span class="aerix-brand-x" style="background:linear-gradient(135deg,#ffffff 12%,#9d55ff 52%,#18cfff 92%);background-clip:text;-webkit-background-clip:text;color:transparent">X</span></h1><p>Control Beyond Touch</p></div><button type="button" class="aerix-start-mouse" data-action="start" aria-label="Start AERIX dashboard"><span class="aerix-start-halo"></span><span class="aerix-start-model-host"></span></button><button type="button" class="aerix-start-cta" data-action="start">Click to Start</button></section>`;
  }

  function nav() {
    const links=[['dashboard','▦','Dashboard'],['gestures','☝','Gestures'],['calibration','◎','Calibration'],['settings','⚙','Settings']];
    return `<aside class="sidebar"><div class="logo-section"><div class="logo-icon">⌁</div><div><h2>AERIX</h2><span>Control Beyond Touch</span></div></div><div class="nav-title">CONTROL CENTER</div><nav>${links.map(([id,i,label])=>`<button class="nav-item ${state.page===id?'nav-active':''}" data-page="${id}">${icon(i)}<span>${label}</span></button>`).join('')}</nav><div class="sidebar-bottom">${icon('✦')}<div><strong>AI Engine</strong><p>Ready for interaction</p></div><span class="online-dot"></span></div></aside>`;
  }
  function syncSidebarActive() {
    app.querySelectorAll('.sidebar [data-page]').forEach(item => {
      const active = item.dataset.page === state.page;
      item.classList.toggle('nav-active', active);
      item.setAttribute('aria-current', active ? 'page' : 'false');
    });
  }
  function topbar() { return `<header class="topbar"><div><p class="eyebrow">CONTROL CENTER</p><h1>Touch-Free Mouse Control</h1></div><div class="topbar-actions"><div class="mode-badge"><span class="small-dot"></span>${friendly(state.mode)} Mode</div><div class="system-badge">${icon('⌁')} ${state.status}</div>${button('lock',`${icon(state.locked?'⌁':'▣')} ${state.locked?'Unlock Control':'Safety Lock'}`,`lock-button ${state.locked?'locked':''}`)}</div></header>`; }
  function hero() { const action=({left_click:'left',right_click:'right',double_click:'double',scroll:'wheel',hscroll:'wheel',zoom:'zoom'})[state.stats.gesture]||''; return `<section class="aerix-hero ${state.locked?'aerix-locked':''}"><div class="aerix-copy"><span class="section-label">TOUCHLESS PRECISION</span><h1>Move through air.<br><em>Command with intent.</em></h1><p>Real-time gestures become seamless computer control.</p></div><div class="aerix-stage action-${action}"><i class="aerix-trail t1"></i><i class="aerix-trail t2"></i><i class="aerix-trail t3"></i><i class="aerix-ring"></i><div class="aerix-mouse"><b class="aerix-body"></b><b class="aerix-button left-button"></b><b class="aerix-button right-button"></b><b class="aerix-seam"></b><b class="aerix-wheel"><i></i></b><b class="aerix-led"></b><b class="aerix-base"></b></div><span class="aerix-lock">⌑ LOCKED</span></div><div class="aerix-signal"><i></i> ${state.stats.gesture==='none'?'Awaiting gesture signal':`Gesture detected · ${friendly(state.stats.gesture)}`}</div></section>`; }
  function camera() { return `<div class="camera-card" data-camera><div class="card-header"><div><span class="section-label">LIVE INPUT</span><h3>Camera Feed</h3></div><div class="camera-status ${state.locked?'offline':''}"><span>●</span>${state.locked?'Paused':'Live'}</div></div><div class="camera-screen"><img class="camera-feed" src="/api/video-feed" alt="Live hand-tracking camera feed"><div class="camera-grid"></div><div class="camera-placeholder"><span>◉</span><h4>${state.locked?'Control Locked':'Camera Ready'}</h4><p>Waiting for the backend camera feed...</p></div><i class="camera-corner top-left"></i><i class="camera-corner top-right"></i><i class="camera-corner bottom-left"></i><i class="camera-corner bottom-right"></i>${button('fullscreen','⛶','fullscreen-button')}<div class="camera-overlay"><span>CAM 01</span><span>640 × 480</span></div></div></div>`; }
  function card(label,value,unit,description) { return `<div class="stat-card"><div class="stat-icon">◈</div><div class="stat-content"><span>${label}</span><div class="stat-value"><strong>${value}</strong><small>${unit}</small></div><p>${description}</p></div></div>`; }
  function toggle(action,on) { return button(action,'<span></span>',`switch ${on?'switch-on':''}`); }
  function sensitivity() { return `<div class="sensitivity-card"><div class="section-heading"><div><span class="section-label">CURSOR CONTROL</span><h3>Movement Sensitivity</h3></div><div class="sensitivity-value">${state.sensitivity}%</div></div><div class="slider-container">${icon('≋')}<input type="range" min="0" max="100" value="${state.sensitivity}" data-sensitivity><span>100</span></div><div class="sensitivity-footer"><div class="adaptive-control"><div class="adaptive-icon">ϟ</div><div><strong>Adaptive Sensitivity</strong><span>Automatically adjust based on movement</span></div></div>${toggle('adaptive',state.adaptive)}</div></div>`; }
  function activity() { const safety=state.clickSafety||{}, warning=safety.warning; return `<div class="click-safety-status ${safety.status==='ACTIVE'?'is-active':'is-limited'}"><span></span>AI Protection: ${safety.status||'LIMITED'}</div>${warning?`<aside class="click-safety-warning" role="alert"><div class="warning-title">⚠ DANGER</div><strong>Potentially unsafe click detected.</strong><p>Reason: ${warning.reason}</p>${button('dismiss-safety','Dismiss')}</aside>`:''}<section class="safety-test-card" aria-label="Safety test targets"><span class="section-label">TEST MODE · SIMULATED TARGETS ONLY</span><h3>Click Protection Test Bench</h3><p>These are harmless simulations: no malware, download, or live phishing website is used.</p><div class="safety-test-actions"><button type="button" class="safety-test-safe" data-action="test-safe" data-safety-url="http://127.0.0.1:8000/#safe-test-passed">SAFE TEST</button><button type="button" class="danger-test safety-test-danger" data-action="test-danger" data-safety-url="safety-test://simulated-phishing">DANGER TEST · Simulated phishing target</button></div></section><div class="activity-card"><div class="section-heading"><div><span class="section-label">SYSTEM ACTIVITY</span><h3>Recent Actions</h3></div><span class="activity-live">● Live</span></div><div class="activity-list">${state.activities.map(a=>`<div class="activity-item"><div class="activity-icon">◉</div><div class="activity-info"><strong>${friendly(a)}</strong><span>Gesture detected</span></div><time>Just now</time></div>`).join('')}</div></div>`; }
  function dashboard() { const s=state.stats; return `<section class="dashboard">${hero()}<div class="welcome-row"><div><span class="section-label">OVERVIEW</span><h2>System Overview</h2><p>Control your computer naturally using real-time hand gestures.</p></div><div class="status-pill ${state.locked?'status-locked':''}"><span></span>${state.locked?'Safety Lock Enabled':'System Active'}</div></div><div class="dashboard-grid">${camera()}<div class="stats-grid">${card('TRACKING FPS',s.fps,'FPS','Real-time tracking')}${card('LATENCY',s.latency,'ms','Response time')}${card('CONFIDENCE',s.confidence,'%','Gesture accuracy')}${card('SENSITIVITY',state.sensitivity,'%','Cursor response')}</div></div><div class="current-gesture"><div><span class="section-label">DETECTED GESTURE</span><h3>${state.locked?'Control Locked':friendly(s.gesture)}</h3></div><div class="gesture-indicator"><span></span>${state.locked?'Paused':'Tracking'}</div></div><div class="hand-control-card"><div class="hand-control-icon">✋</div><div class="hand-control-content"><span class="section-label">CONTROL MODE</span><h3>Hand Gesture Control</h3><p>Mouse operations are controlled entirely through real-time hand gestures.</p></div><div class="hand-control-status"><span></span>HAND ONLY</div></div><div class="control-grid"><div class="safety-card ${state.locked?'safety-locked':''}"><div class="safety-icon">${state.locked?'▣':'✓'}</div><div class="safety-content"><span class="section-label">SAFETY CONTROL</span><h3>${state.locked?'Mouse Control Locked':'Mouse Control Active'}</h3><p>${state.locked?'Gesture actions are temporarily disabled.':'Gesture commands can currently control the cursor.'}</p></div>${button('lock',state.locked?'Unlock':'Lock','safety-toggle')}</div>${sensitivity()}</div>${activity()}</section>`; }
  const gestureRows=[['Fist (all four fingers folded)','lock','Hold briefly to toggle Safety Lock once. Release before locking or unlocking again.'],['Index + pinky extended (rock sign)','zoom','Move hand up to zoom in or down to zoom out.'],['Index + middle + ring extended; pinky folded','hscroll','Move hand left or right for horizontal scrolling.'],['Two fingers: index + middle extended (V sign)','scroll','Move immediately up or down for vertical scrolling.'],['Thumb touches index and middle together','double_click','Double click at the current cursor position.'],['Right hand: thumb + index pinch','left_click','Left click.'],['Right hand: thumb + middle pinch','right_click','Right click.'],['Left hand: thumb + index pinch','right_click','Right click.'],['Left hand: thumb + middle pinch','left_click','Left click.'],['Index finger extended','move','Move the calibrated cursor with the index fingertip.'],['Thumb + index + middle pinch','select_drag','Pinch thumb, index, and middle fingers to select. Hold for about 0.5 seconds to start dragging. Move while maintaining the pinch, then release to drop.'],['Open palm, quick swipe right','tab_next','Switch to the next browser tab (Ctrl + Tab), once per swipe.'],['Open palm, quick swipe left','tab_previous','Switch to the previous browser tab (Ctrl + Shift + Tab), once per swipe.'],['Crossed index + middle fingers','browser_back','Go back in the browser (Alt + Left), once each time the crossed pose is made.']];
  function gestures() { return `<section class="page-section"><div class="page-heading"><div><span class="section-label">HAND GESTURE ENGINE</span><h2>Gesture Controls</h2><p>Hand gestures used to control the mouse in real time.</p></div></div><div class="gesture-table-wrapper"><table class="gesture-table"><thead><tr><th>#</th><th>Hand Gesture</th><th>Action</th><th>Description</th><th>Status</th></tr></thead><tbody>${gestureRows.map((r,i)=>`<tr><td class="gesture-number">${i+1}</td><td><div class="gesture-name"><div class="gesture-table-icon">☝</div><span>${r[0]}</span></div></td><td><code class="gesture-action-code">${r[1]}</code></td><td class="gesture-description">${r[2]}</td><td><span class="gesture-enabled"><span></span>Enabled</span></td></tr>`).join('')}</tbody></table></div><div class="gesture-note">⚠<div><strong>Safety behaviour</strong><p>If no hand is detected for 5 or more frames, the system force-releases drag and resets gesture tracking.</p></div></div></section>`; }
  function calibration() { const c=state.calibration, n=c.points||0, pts=['Top Left','Top Right','Bottom Right','Bottom Left']; return `<section class="page-section"><div class="page-heading"><div><span class="section-label">SYSTEM SETUP</span><h2>Camera Calibration</h2><p>Calibrate the hand tracking area for accurate cursor movement.</p></div><div class="calibration-progress">${n}/4 Points</div></div><div class="calibration-layout"><div class="calibration-camera"><div class="card-header"><div><span class="section-label">CALIBRATION AREA</span><h3>Position your hand</h3></div>◉</div><div class="calibration-screen"><img class="camera-feed" src="/api/video-feed" alt="Live calibration camera feed"><div class="calibration-grid"></div>${['tl','tr','br','bl'].map((p,i)=>`<div class="calibration-point point-${p} ${n===i&&c.active?'active':''}"></div>`).join('')}<div class="calibration-center"><span>◎</span><strong>${c.complete?'Calibration Complete':c.active?`Move to ${c.current_point||pts[n]}`:'Ready to Calibrate'}</strong><span>${c.complete?'Your tracking area is ready.':'Follow the highlighted point, then confirm it.'}</span></div></div>${button('calibrate',c.complete?'✓ Calibration Complete':c.active?'◎ Confirm Point':'◎ Start Calibration','primary-button calibration-button')}</div><div class="calibration-info"><div class="info-card"><span class="section-label">HOW IT WORKS</span><h3>Four-point calibration</h3><p>Place your hand at each highlighted point. The system will map your camera space to the screen coordinates.</p><div class="calibration-steps">${pts.map((p,i)=>`<div class="calibration-step ${i<n?'completed':''} ${i===n?'current':''}"><div class="step-number">${i<n?'✓':i+1}</div><div><strong>${p}</strong><span>${i<n?'Completed':c.active&&i===n?'Current point':'Waiting'}</span></div></div>`).join('')}</div>${c.error?`<p class="calibration-error">${c.error}</p>`:''}${button('reset-calibration','↻ Recalibrate','secondary-button full-width')}</div></div></div></section>`; }
  function settings() { return `<section class="page-section"><div class="page-heading"><div><span class="section-label">CONFIGURATION</span><h2>System Settings</h2><p>Configure camera, hand tracking and safety preferences.</p></div></div><div class="settings-grid"><div class="settings-card"><div class="settings-card-heading"><div class="settings-icon">◉</div><div><span class="section-label">INPUT</span><h3>Camera</h3></div></div><label>Camera Device</label><select><option>Default Camera</option><option>Camera 01</option><option>Camera 02</option></select><div class="setting-status"><span class="status-indicator"></span>Camera ready for hand tracking</div></div><div class="settings-card"><div class="settings-card-heading"><div class="settings-icon">≋</div><div><span class="section-label">CURSOR</span><h3>Sensitivity</h3></div></div><div class="settings-slider-row"><span>Movement sensitivity</span><strong>${state.sensitivity}%</strong></div><input class="settings-range" type="range" min="30" max="100" value="${state.sensitivity}" data-sensitivity><div class="setting-description">ϟ Adjust how much index-finger movement affects cursor movement.</div></div><div class="settings-card"><div class="settings-card-heading"><div class="settings-icon">✓</div><div><span class="section-label">SAFETY</span><h3>Safety Controls</h3></div></div><div class="setting-row"><div><strong>Adaptive Sensitivity</strong><p>Automatically adjust cursor response.</p></div>${toggle('adaptive',state.adaptive)}</div><div class="setting-row"><div><strong>Hand Gesture Engine</strong><p>Enable real-time hand recognition.</p></div>${toggle('engine',state.status==='Active')}</div></div><div class="settings-card"><div class="settings-card-heading"><div class="settings-icon">▦</div><div><span class="section-label">SYSTEM</span><h3>System Information</h3></div></div><div class="system-info-grid"><div><span>Control Mode</span><strong>Hand Gestures</strong></div><div><span>Tracking</span><strong>MediaPipe</strong></div><div><span>Camera</span><strong>OpenCV</strong></div><div><span>Mouse</span><strong>PyAutoGUI</strong></div></div></div></div></section>`; }
  function render() { if(!state.entered){app.innerHTML=startPage();const mouse=app.querySelector('.aerix-start-mouse'),cta=app.querySelector('.aerix-start-cta');mouse.onclick=e=>{if(e.detail===0||!mouse.dataset.dragging)startDashboard();};cta.onclick=startDashboard;requestAnimationFrame(()=>{window.initAerixStartMouse?.();window.initAerixCursor?.();});return;} const content=state.page==='dashboard'?dashboard():state.page==='gestures'?gestures():state.page==='calibration'?calibration():settings(); const main=`<main class="main-content">${topbar()}${content}</main>`; const existingMain=app.querySelector('.main-content'); if(existingMain)existingMain.outerHTML=main;else app.innerHTML=nav()+main; syncSidebarActive(); app.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>act(b.dataset.action));app.querySelectorAll('[data-sensitivity]').forEach(i=>i.oninput=()=>{state.sensitivity=+i.value;render();});requestAnimationFrame(()=>window.initAerixDashboardCursor?.()); }
  async function act(a) { if(a==='start'){startDashboard();return;}if(a==='test-safe'||a==='test-danger'){await runSafetyTest(a==='test-safe'?'safe':'danger');return;}if(a==='dismiss-safety'){try{const r=await fetch('/api/safety/dismiss',{method:'POST'});if(r.ok)state.clickSafety=await r.json();}catch{}render();return;}if(a==='adaptive'){state.adaptive=!state.adaptive;render();return;}if(a==='engine'){state.status=state.status==='Active'?'Paused':'Active';render();return;}if(a==='fullscreen'){const c=app.querySelector('[data-camera]');try{document.fullscreenElement?await document.exitFullscreen():await c.requestFullscreen();}catch{}return;}let url=a==='lock'?'/api/lock':a==='calibrate'?(state.calibration.active?'/api/calibrate/point':'/api/calibrate'):'/api/calibrate/reset';try{const r=await fetch(url,{method:'POST'});if(!r.ok)throw Error();const data=await r.json();if(a==='lock')state.locked=data.locked;else state.calibration=data;}catch{state.status='Backend unavailable';state.calibration={...state.calibration,error:'The backend unavailable'};}render(); }
  async function runSafetyTest(target) { try { const r=await fetch(`/api/safety/test-click/${target}`,{method:'POST'}); if(!r.ok)throw Error(); const data=await r.json(); state.clickSafety=data.click_safety; console.log(`CLICK DETECTED → ANALYZING → ${data.allowed?'SAFE → CLICK ALLOWED':'DANGEROUS → CLICK BLOCKED'}`); } catch { state.status='Backend unavailable'; } render(); }
  function apply(data) { state.locked=!!data.locked;state.mode=data.mode||'gesture';state.calibration=data.calibration||state.calibration;state.clickSafety=data.click_safety||state.clickSafety;state.stats={fps:data.fps||0,latency:data.latency_ms||0,confidence:Math.round((data.confidence||0)*100),gesture:data.gesture||'none'};if(data.gesture&&data.gesture!=='none'&&data.gesture!==state.lastGesture)state.activities=[data.gesture,...state.activities].slice(0,5);state.lastGesture=data.gesture||'none';render(); }
  let lastReportedTarget;
  // The sidebar is retained while page content is replaced by render().
  // Delegate its click once from the stable app root so a navigation button
  // always reaches state updates, even during a WebSocket-driven re-render.
  app.addEventListener('click', event => {
    const button = event.target.closest?.('.sidebar [data-page]');
    if (!button || !state.entered) return;
    state.page = button.dataset.page;
    history.pushState({ page: state.page }, '', `#${state.page}`);
    render();
  });
  const updatePageFromUrl = () => {
    const page = pageFromLocation();
    if (page === state.page) return;
    state.page = page;
    if (state.entered) render();
  };
  window.addEventListener('popstate', updatePageFromUrl);
  window.addEventListener('hashchange', updatePageFromUrl);
  document.addEventListener('pointermove', event => { if(!state.entered)return; const target=event.target.closest?.('[data-safety-url], a[href]'), url=target?.dataset.safetyUrl||target?.href||null; if(url===lastReportedTarget)return; lastReportedTarget=url; if(target?.classList.contains('safety-test-safe'))console.log('TEST MODE: SAFE TARGET ARMED'); if(target?.classList.contains('safety-test-danger'))console.log('TEST MODE: DANGEROUS TARGET ARMED'); fetch('/api/safety/target',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url})}).catch(()=>{}); }, {passive:true});
  function connect(){const protocol=location.protocol==='https:'?'wss:':'ws:';const ws=new WebSocket(`${protocol}//${location.host}/ws`);ws.onopen=()=>{state.status='Connected';render();};ws.onmessage=e=>apply(JSON.parse(e.data));ws.onclose=()=>{state.status='Reconnecting';render();setTimeout(connect,1500);};ws.onerror=()=>ws.close();}
  function startDashboard(){if(state.entered||state.starting)return;state.starting=true;const landing=app.querySelector('.aerix-start-page');landing?.classList.add('aerix-start-exit');setTimeout(()=>{state.entered=true;window.destroyAerixStartMouse?.();window.destroyAerixCursor?.();render();fetch('/api/status').then(r=>r.ok?r.json():Promise.reject()).then(apply).catch(()=>{state.status='Backend unavailable';render();});connect();},260);}
  render();
})();
